version: "3.9"  # optional since v1.27.0
services:
  server:
    build:
        context: .
        dockerfile: Dockerfile-server
    ports:
      - "3050:3050"
    volumes:
      - "/mnt/c/Users/David.Desmaisons/Pictures/wallpaper/Photo:/usr/src/app/images:rw"
  ui:
    build:
        context: .
        dockerfile: Dockerfile-ui
    ports:
        - "8090:80"